"""Tests for Phase 6 — postmortem learning loop."""
import asyncio
import os
import sys
import tempfile
import types as _types

import pytest

# ---------------------------------------------------------------------------
# Isolate from ADK import chain (same pattern as previous phases)
# ---------------------------------------------------------------------------
_ROOT = os.path.dirname(os.path.dirname(__file__))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

if "opsmind" not in sys.modules:
    _pkg = _types.ModuleType("opsmind")
    _pkg.__path__ = [os.path.join(_ROOT, "opsmind")]
    _pkg.__package__ = "opsmind"
    sys.modules["opsmind"] = _pkg

# Stub google.adk.tools.tool_context
_google = _types.ModuleType("google")
_google_adk = _types.ModuleType("google.adk")
_google_adk_tools = _types.ModuleType("google.adk.tools")
_google_adk_tools_tc = _types.ModuleType("google.adk.tools.tool_context")


class _FakeToolContext:
    def __init__(self):
        self.state: dict = {}


_google_adk_tools_tc.ToolContext = _FakeToolContext
sys.modules.setdefault("google", _google)
sys.modules.setdefault("google.adk", _google_adk)
sys.modules.setdefault("google.adk.tools", _google_adk_tools)
sys.modules.setdefault("google.adk.tools.tool_context", _google_adk_tools_tc)

# Stub opsmind.config — point OUTPUT_DIR at a temp dir so weights file is isolated
import logging as _logging
_tmp_output = tempfile.mkdtemp(prefix="opsmind_test_")
_cfg = _types.ModuleType("opsmind.config")
_cfg.logger = _logging.getLogger("test_postmortem")
_cfg.MODEL_NAME = "gemini-2.0-flash-001"
_cfg.OUTPUT_DIR = _tmp_output
_cfg.GCP_STORAGE_ENABLED = False
sys.modules["opsmind.config"] = _cfg

# Stub opsmind.tools.guardrail — no-op pass-through
_guardrail_mod = _types.ModuleType("opsmind.tools.guardrail")
_guardrail_mod.with_guardrail = lambda fn: fn
_tools_pkg = _types.ModuleType("opsmind.tools")
_tools_pkg.__path__ = [os.path.join(_ROOT, "opsmind", "tools")]
_tools_pkg.__package__ = "opsmind.tools"
sys.modules["opsmind.tools"] = _tools_pkg
sys.modules["opsmind.tools.guardrail"] = _guardrail_mod

# Stub opsmind.utils (needed by postmortems.py)
_utils_mod = _types.ModuleType("opsmind.utils")
_utils_mod.upload_file_to_gcp = lambda **kw: {"status": "error", "message": "stub"}
_utils_mod.generate_download_link = lambda **kw: {"status": "error", "message": "stub"}
_utils_mod.list_postmortem_files_in_gcp = lambda: {"status": "error", "message": "stub"}
sys.modules["opsmind.utils"] = _utils_mod

# Now safe to import Phase 6 modules
from opsmind.tools.learning import (  # noqa: E402
    ingest_postmortem,
    mark_resolution_helpful,
    get_knowledge_stats,
    _parse_markdown_sections,
    _load_weights,
    _save_weights,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run(coro):
    return asyncio.get_event_loop().run_until_complete(coro)


def ctx():
    return _FakeToolContext()


_SAMPLE_POSTMORTEM = """\
# Incident Postmortem: INC0000001

## Executive Summary
This postmortem analyzes incident INC0000001 using evidence-grounded root cause analysis.
RCA confidence: **80%**. Evidence sources: [INC-0001][JIRA-WW-100]

## Incident Details
- **Incident ID**: INC0000001
- **Category**: network
- **Priority**: P1
- **Description**: nginx upstream timeout caused 502 errors

## Root Cause Analysis

**Root Cause**: Misconfigured nginx upstream timeout [INC-0001]

### Contributing Factors
- nginx timeout mismatch (confidence: 80%) [INC-0001]
- upstream service degraded (confidence: 60%) [JIRA-WW-100]

## Related Jira Issues
### WW-100 [JIRA-WW-100]
- **Summary**: Nginx timeout config
- **Status**: Resolved
- **Priority**: High

## Lessons Learned
- Timeouts must be tuned per-service.
- Certificate expiry is 100% predictable.

## Action Items
1. Tune nginx upstream timeout thresholds.
2. Update runbooks and incident response playbooks.

---
*Generated by OpsMind on 2024-01-01 00:00:00*
"""


def _write_postmortem(content: str = _SAMPLE_POSTMORTEM) -> str:
    """Write sample postmortem to a temp file and return its path."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as f:
        f.write(content)
        return f.name


# ---------------------------------------------------------------------------
# _parse_markdown_sections
# ---------------------------------------------------------------------------

def test_parse_sections_finds_headings():
    sections = _parse_markdown_sections(_SAMPLE_POSTMORTEM)
    headings = [s["heading"] for s in sections]
    assert any("Executive Summary" in h for h in headings)
    assert any("Root Cause" in h for h in headings)


def test_parse_sections_no_headings_returns_single():
    sections = _parse_markdown_sections("plain text with no headings")
    assert len(sections) == 1
    assert sections[0]["heading"] == "full_document"


def test_parse_sections_empty_returns_single():
    sections = _parse_markdown_sections("")
    assert len(sections) == 1


def test_parse_sections_content_preserved():
    sections = _parse_markdown_sections(_SAMPLE_POSTMORTEM)
    all_content = " ".join(s["content"] for s in sections)
    assert "nginx" in all_content.lower()
    assert "INC0000001" in all_content


# ---------------------------------------------------------------------------
# ingest_postmortem
# ---------------------------------------------------------------------------

def test_ingest_postmortem_success():
    """Roadmap: ingest_postmortem returns status=success with chunks_added >= 1."""
    path = _write_postmortem()
    result = ingest_postmortem(path, "INC0000001")
    assert result["status"] == "success", result.get("message")
    assert result["chunks_added"] >= 1
    assert result["incident_id"] == "INC0000001"


def test_ingest_postmortem_increases_document_count():
    """Roadmap: after ingestion, get_knowledge_stats total_documents increases."""
    stats_before = get_knowledge_stats()
    before = stats_before.get("total_documents", 0)

    path = _write_postmortem()
    result = ingest_postmortem(path, "INC0000002")
    assert result["status"] == "success"

    stats_after = get_knowledge_stats()
    after = stats_after.get("total_documents", 0)
    assert after > before, f"Expected doc count to increase: {before} → {after}"


def test_ingest_postmortem_source_tagged_as_postmortem():
    """Ingested chunks must have source='postmortem'."""
    from opsmind.retrieval.hybrid import _get_retriever
    path = _write_postmortem()
    ingest_postmortem(path, "INC0000003")
    retriever = _get_retriever()
    postmortem_docs = [d for d in retriever._docs if d.get("source") == "postmortem"]
    assert len(postmortem_docs) >= 1


def test_ingest_postmortem_metadata_has_incident_id():
    """Each ingested chunk must carry incident_id in metadata."""
    from opsmind.retrieval.hybrid import _get_retriever
    path = _write_postmortem()
    ingest_postmortem(path, "INC0000004")
    retriever = _get_retriever()
    matching = [
        d for d in retriever._docs
        if d.get("source") == "postmortem" and d.get("incident_id") == "INC0000004"
    ]
    assert len(matching) >= 1


def test_ingest_postmortem_file_not_found():
    result = ingest_postmortem("/nonexistent/path/postmortem.md", "INC0000099")
    assert result["status"] == "error"
    assert "not found" in result["message"].lower()


def test_ingest_postmortem_empty_file():
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as f:
        f.write("   ")
        path = f.name
    result = ingest_postmortem(path, "INC0000098")
    assert result["status"] == "error"


def test_ingest_postmortem_returns_total_documents():
    path = _write_postmortem()
    result = ingest_postmortem(path, "INC0000005")
    assert "total_documents" in result
    assert result["total_documents"] >= result["chunks_added"]


def test_ingest_postmortem_searchable_after_ingestion():
    """Roadmap: search_knowledge_base can surface content from a saved postmortem."""
    from opsmind.retrieval.hybrid import search
    path = _write_postmortem()
    ingest_postmortem(path, "INC0000006")
    results = search("nginx upstream timeout 502", k=5)
    # At least one result should come from the ingested postmortem
    sources = [r.source for r in results]
    assert "postmortem" in sources, f"Expected postmortem in sources, got: {sources}"


# ---------------------------------------------------------------------------
# mark_resolution_helpful
# ---------------------------------------------------------------------------

def test_mark_resolution_helpful_true():
    """Roadmap: mark_resolution_helpful stores weight."""
    # Use isolated weights file via patched OUTPUT_DIR
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    _learning._WEIGHTS_FILE = os.path.join(_tmp_output, "test_weights_helpful.json")
    try:
        result = mark_resolution_helpful("INC0000010", helpful=True)
        assert result["status"] == "success"
        assert result["weight"] == 1
        assert result["helpful"] is True
    finally:
        _learning._WEIGHTS_FILE = orig


def test_mark_resolution_helpful_false():
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    _learning._WEIGHTS_FILE = os.path.join(_tmp_output, "test_weights_unhelpful.json")
    try:
        result = mark_resolution_helpful("INC0000011", helpful=False)
        assert result["status"] == "success"
        assert result["weight"] == -1
        assert result["helpful"] is False
    finally:
        _learning._WEIGHTS_FILE = orig


def test_mark_resolution_helpful_accumulates():
    """Multiple helpful marks accumulate weight."""
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    _learning._WEIGHTS_FILE = os.path.join(_tmp_output, "test_weights_accum.json")
    try:
        mark_resolution_helpful("INC0000012", helpful=True)
        mark_resolution_helpful("INC0000012", helpful=True)
        result = mark_resolution_helpful("INC0000012", helpful=True)
        assert result["weight"] == 3
    finally:
        _learning._WEIGHTS_FILE = orig


def test_mark_resolution_helpful_mixed():
    """helpful + unhelpful cancel out."""
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    _learning._WEIGHTS_FILE = os.path.join(_tmp_output, "test_weights_mixed.json")
    try:
        mark_resolution_helpful("INC0000013", helpful=True)
        mark_resolution_helpful("INC0000013", helpful=True)
        result = mark_resolution_helpful("INC0000013", helpful=False)
        assert result["weight"] == 1
    finally:
        _learning._WEIGHTS_FILE = orig


def test_mark_resolution_helpful_persists():
    """Weight survives a reload from disk."""
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    wf = os.path.join(_tmp_output, "test_weights_persist.json")
    _learning._WEIGHTS_FILE = wf
    try:
        mark_resolution_helpful("INC0000014", helpful=True)
        mark_resolution_helpful("INC0000014", helpful=True)
        # Reload from disk
        weights = _load_weights.__wrapped__() if hasattr(_load_weights, "__wrapped__") else _learning._load_weights()
        assert weights["INC0000014"]["weight"] == 2
    finally:
        _learning._WEIGHTS_FILE = orig


# ---------------------------------------------------------------------------
# get_knowledge_stats
# ---------------------------------------------------------------------------

def test_get_knowledge_stats_returns_required_fields():
    """Roadmap: get_knowledge_stats returns total_documents, sources, postmortem_count."""
    result = get_knowledge_stats()
    assert result["status"] == "success"
    for key in ["total_documents", "sources", "postmortem_count", "index_loaded"]:
        assert key in result, f"Missing key: {key}"


def test_get_knowledge_stats_postmortem_count_increases():
    """Roadmap: after ingestion, postmortem_count in stats increases."""
    stats_before = get_knowledge_stats()
    before = stats_before.get("postmortem_count", 0)

    path = _write_postmortem()
    ingest_postmortem(path, "INC0000020")

    stats_after = get_knowledge_stats()
    after = stats_after.get("postmortem_count", 0)
    assert after > before


def test_get_knowledge_stats_top_weighted_reflects_marks():
    """Roadmap: get_knowledge_stats reflects helpful marks in top_weighted."""
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    _learning._WEIGHTS_FILE = os.path.join(_tmp_output, "test_weights_stats.json")
    try:
        mark_resolution_helpful("INC0000030", helpful=True)
        mark_resolution_helpful("INC0000030", helpful=True)
        mark_resolution_helpful("INC0000030", helpful=True)
        stats = get_knowledge_stats()
        top = stats.get("top_weighted", [])
        assert len(top) >= 1
        top_ids = [t["incident_id"] for t in top]
        assert "INC0000030" in top_ids
    finally:
        _learning._WEIGHTS_FILE = orig


def test_get_knowledge_stats_sources_is_dict():
    result = get_knowledge_stats()
    assert isinstance(result["sources"], dict)


# ---------------------------------------------------------------------------
# save_postmortem integration — triggers ingestion
# ---------------------------------------------------------------------------

def test_save_postmortem_triggers_ingestion():
    """
    Roadmap: save_postmortem auto-triggers ingest_postmortem after successful save.
    After save, postmortem_count in stats must increase.
    """
    # Force fresh import of postmortems with our stubs
    for mod in list(sys.modules.keys()):
        if "postmortem" in mod or "learning" in mod:
            del sys.modules[mod]

    from opsmind.tools.postmortems import save_postmortem
    from opsmind.tools.learning import get_knowledge_stats

    stats_before = get_knowledge_stats()
    before = stats_before.get("postmortem_count", 0)

    tc = ctx()
    result = run(save_postmortem(tc, "INC0000040", _SAMPLE_POSTMORTEM))
    assert result["status"] == "success"

    stats_after = get_knowledge_stats()
    after = stats_after.get("postmortem_count", 0)
    assert after > before, f"Expected postmortem_count to increase: {before} → {after}"


def test_save_postmortem_local_file_exists():
    """save_postmortem still writes the .md file (storage preserved)."""
    for mod in list(sys.modules.keys()):
        if "postmortem" in mod:
            del sys.modules[mod]

    from opsmind.tools.postmortems import save_postmortem

    tc = ctx()
    result = run(save_postmortem(tc, "INC0000041", _SAMPLE_POSTMORTEM))
    assert result["status"] == "success"
    filepath = result.get("filepath", "")
    if filepath:
        assert os.path.exists(filepath)


def test_list_postmortem_files_still_works():
    """Roadmap: list_postmortem_files still works unchanged (no regression)."""
    for mod in list(sys.modules.keys()):
        if "postmortem" in mod:
            del sys.modules[mod]

    from opsmind.tools.postmortems import save_postmortem, list_postmortem_files

    tc = ctx()
    run(save_postmortem(tc, "INC0000042", _SAMPLE_POSTMORTEM))
    list_result = run(list_postmortem_files(tc))
    assert list_result["status"] == "success"
    assert isinstance(list_result["files"], list)
    assert list_result["count"] >= 1


# ---------------------------------------------------------------------------
# Full learning loop integration
# ---------------------------------------------------------------------------

def test_full_learning_loop():
    """
    Roadmap acceptance: save → ingest → search surfaces postmortem content.
    """
    from opsmind.retrieval.hybrid import search

    path = _write_postmortem(
        "# Incident Postmortem: INC0000050\n\n"
        "## Root Cause Analysis\n\n"
        "**Root Cause**: Redis maxmemory-policy not configured caused OOM eviction.\n\n"
        "## Lessons Learned\n"
        "- Redis without a maxmemory policy will consume all available RAM.\n"
    )
    result = ingest_postmortem(path, "INC0000050")
    assert result["status"] == "success"
    assert result["chunks_added"] >= 1

    # Search for content from the ingested postmortem
    results = search("redis maxmemory OOM eviction", k=10)
    sources = [r.source for r in results]
    assert "postmortem" in sources


def test_helpful_mark_then_stats():
    """mark_resolution_helpful → get_knowledge_stats shows it in top_weighted."""
    import opsmind.tools.learning as _learning
    orig = _learning._WEIGHTS_FILE
    _learning._WEIGHTS_FILE = os.path.join(_tmp_output, "test_weights_loop.json")
    try:
        mark_resolution_helpful("INC0000060", helpful=True)
        mark_resolution_helpful("INC0000060", helpful=True)
        stats = get_knowledge_stats()
        top_ids = [t["incident_id"] for t in stats.get("top_weighted", [])]
        assert "INC0000060" in top_ids
    finally:
        _learning._WEIGHTS_FILE = orig
